version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydbusr
      POSTGRES_PASSWORD: P@ssWord123
    ports:
      - "5432:5432"
    volumes:
#      - pgdata:/var/lib/postgresql/data # ✅ fix mount path # Docker-managed volume
      - ./my-local-pgdata:/var/lib/postgresql/data
    networks:
      - spring-cloud-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - spring-cloud-network

  message-server:
    container_name: message-server
    build:
      context: ./message-server
      dockerfile: Dockerfile
    image: message-server:latest
    restart: unless-stopped
    ports:
      - "18888:8080"
    depends_on:
      - postgres
    networks:
      - spring-cloud-network

  product-server:
    container_name: product-server
    build:
      context: ./product-server
      dockerfile: Dockerfile
    image: product-server:latest
    restart: unless-stopped
    ports:
      - "19999:8080"
    depends_on:
      - redis
      - postgres
    networks:
      - spring-cloud-network

volumes:
  pgdata:
    driver: local

networks:
  spring-cloud-network:
    driver: bridge
