#version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: mydbusr
      POSTGRES_PASSWORD: P@ssWord123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data
  message-server:
    container_name: message-server
    build:
      context: ./message-server
      dockerfile: Dockerfile
    image: message-server:latest
    restart: unless-stopped
    ports:
      - "18888:8080"
    networks:
      - spring-cloud-network
  product-server:
    container_name: product-server
    build:
      context: ./product-server
      dockerfile: Dockerfile
    image: product-server:latest
    restart: unless-stopped
    ports:
      - "19999:8080"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
      driver: bridge
volumes:
  pgdata:
    driver: local
